import java.util.*;
public class WaitDemo {
    static int number = 0;
    static boolean produced = false;
    static int evenCount = 0;

    public static void main(String[] args) throws Exception {
        Object lock = new Object();

        Thread producer = new Thread(() -> {
            Random rand = new Random();
            for (int i = 0; i < 10; i++) {
                synchronized(lock) {
                    while (produced) {
                        try { lock.wait(); } catch (Exception e) { }
                    }
                    number = rand.nextInt(100) + 1;
                    System.out.println("Number generated by Producer: " + number);
                    produced = true;
                    lock.notify();
                }
            }
        });

        Thread consumer = new Thread(() -> {
            for (int i = 0; i < 10; i++) {
                synchronized(lock) {
                    while (!produced) {
                        try { lock.wait(); } catch (Exception e) { }
                    }
                    if (number % 2 == 0)
                        evenCount++;
                    produced = false;
                    lock.notify();
                }
            }
            System.out.println("Number even numbers received by Consumer: " + evenCount);
        });

        producer.start();
        consumer.start();
        producer.join();
        consumer.join();
    }
}
